name: Mirror to https://github.com/andrewgilliland/kokomo-ui-dev

on:
  push:
    branches:
      - main
      - dev # or all branches with '**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Push to mirror
        run: |
          git remote add mirror https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/andrewgilliland/kokomo-ui-dev.git
          git push --mirror mirror
