name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            npm run build-storybook -- --output-dir ./storybook-static
          else
            npm run build-storybook -- --output-dir ./storybook-static
          fi

      - name: Deploy to GitHub Pages (main branch)
        if: github.ref_name == 'main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          keep_files: true

      - name: Deploy to GitHub Pages (dev branch)
        if: github.ref_name == 'dev'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          destination_dir: dev
          keep_files: true
