name: Test Secret Injection

on:
  workflow_dispatch: # lets you run this manually from the Actions tab

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check secret presence
        run: |
          if [ -z "${{ secrets.MIRROR_TOKEN }}" ]; then
            echo "❌ Secret MIRROR_TOKEN is NOT set!"
            exit 1
          else
            echo "✅ Secret MIRROR_TOKEN is set."
            echo "Length of token: ${#TOKEN}"
          fi
        env:
          TOKEN: ${{ secrets.MIRROR_TOKEN }}
